#                             _____
#      /\                    |  __ \
#     /  \   _ __  _ __   ___| |__) |   _
#    / /\ \ | '_ \| '_ \ / _ \  ___/ | | |
#   / ____ \| | | | | | |  __/ |   | |_| |
#  /_/    \_\_| |_|_| |_|\___|_|    \__, |
#                                    __/ |
#                                   |___/
# Gilberto Charles - 2020
ANNE_LAYOUT = {
    "esc": 0,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9,
    "0": 10,
    "minus": 11,
    "equals": 12,
    "backspace": 13,
    "tab": 14,
    "q": 15,
    "w": 16,
    "e": 17,
    "r": 18,
    "t": 19,
    "y": 20,
    "u": 21,
    "i": 22,
    "o": 23,
    "p": 24,
    "lbracket": 25,
    "rbracket": 26,
    "backslash": 27,
    "caps": 28,
    "a": 29,
    "s": 30,
    "d": 31,
    "f": 32,
    "g": 33,
    "h": 34,
    "j": 35,
    "k": 36,
    "l": 37,
    "semicolon": 38,
    "apostrophe": 39,
    "enter": 40,
    "deadkey1": None,
    "leftshift": 41,
    "deadkey2": None,
    "z": 42,
    "x": 43,
    "c": 44,
    "v": 45,
    "b": 46,
    "n": 47,
    "m": 48,
    "comma": 49,
    "dot": 50,
    "slash": 51,
    "rightshift": 52,
    "deadkey3": None,
    "leftctrl": 53,
    "deadkey4": None,
    "leftsuper": 54,
    "leftalt": 55,
    "deadkey5": None,
    "daedkey6": None,
    "space": 56,
    "deadkey7": None,
    "deadkey8": None,
    "rightalt": 57,
    "fn": 58,
    "context": 59,
    "rightctrl": 60,
    "deadkey9": None
}
